name: Bump version
on:
  push:
    branches:
      - versioning_test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: darioblanco/bump-semver@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prefix: v